export const countryCodeToNameMap = {
	CZ: 'Česká republika',
	SK: 'Slovensko',
	DE: 'Německo',
	HU: 'Maďarsko',
	PL: 'Polsko',
	AT: 'Rakousko',
	IT: 'Itálie',
	FR: 'Francie',
	ES: 'Španělsko',
	PT: 'Portugalsko',
	ZA: 'Jihoafrická republika',
	AR: 'Argentina',
	CL: 'Chile',
	GB: 'Velká Británie',
	IE: 'Irsko',
	MX: 'Mexiko',
	DO: 'Dominikánská republika',
	PA: 'Panama',
	CU: 'Kuba',
	GE: 'Gruzie',
	NZ: 'Nový Zéland',
	CARIBIC: 'Karibik',
	SCOTLAND: 'Skotsko',
} as const;

export const backgroundColorMap = {
	none: null,
	grey: 'var(--vinisto-color-lighter-gray)',
	beige: '242, 232, 211',
	'light pink': '244, 229, 235',
} as const;
