const STORAGE_PREFIX = 'VINISTO_ESHOP';

const LocalStorageKeys = {
	LOGIN_REDIRECT_PATH: 'LOGIN_REDIRECT_PATH',
	ACTIVE_CURRENCY: 'ACTIVE_CURRENCY',
	USER_PRICE_LEVEL: 'USER_PRICE_LEVEL',
	ACTIVE_PLATFORM: 'ACTIVE_PLATFORM',
	CART_SHIPPING_DATA: 'CART_SHIPPING_DATA',
	VINISTO_AUTH: 'VINISTO_AUTH',
	ANONYMOUS_UID: 'ANONYMOUS_UID',
	BASKET_ID: 'BASKET_ID',
	BASKET_TIMER: 'BASKET_TIMER',
	VINISTO_ORDER_FORM: 'VINISTO_ORDER_FORM',
	VINISTO_ORDER_STATE: 'VINISTO_ORDER_STATE',
	COOKIE_DATA: 'COOKIE_DATA',
	ANALYTICS_SENT: 'ANALYTICS_SENT',
	UTM_CAMPAIGN_DATA: 'UTM_CAMPAIGN_DATA',
	WS_CONNECTION_ID: 'WS_CONNECTION_ID',
	EHUB: 'EHUB',
} as const;

export { STORAGE_PREFIX, LocalStorageKeys };
