export const HOME_PAGE_PROMO_CAROUSEL = 'HOME_PAGE_PROMO_CAROUSEL';
export const HOME_PAGE_ARTICLES_CAROUSEL = 'HOME_PAGE_ARTICLES_CAROUSEL';

export const PRIMARY_CARD_ASPECT_RATIO = '500/242';
export const CAROUSEL_MODE_BREAKPOINT = 500;
export const CONTAINER_PADDING_X = 16;
