export const countriesAndTerritoriesDictionary = {
	afghanistan: 'af',
	albanie: 'al',
	alzirsko: 'dz',
	andorra: 'ad',
	angola: 'ao',
	'antigua-a-barbuda': 'ag',
	argentina: 'ar',
	armenie: 'am',
	australie: 'au',
	azerbajdzan: 'az',
	bahamy: 'bs',
	bahrajn: 'bh',
	banglades: 'bd',
	barbados: 'bb',
	belgie: 'be',
	belize: 'bz',
	belorusko: 'by',
	benin: 'bj',
	bhutan: 'bt',
	bolivie: 'bo',
	'bosna-a-hercegovina': 'ba',
	botswana: 'bw',
	brazilie: 'br',
	brunej: 'bn',
	bulharsko: 'bg',
	'burkina-faso': 'bf',
	burundi: 'bi',
	cad: 'td',
	'cerna-hora': 'me',
	cesko: 'cz',
	'ceska-republika': 'cz',
	cina: 'cn',
	dansko: 'dk',
	dominika: 'dm',
	'dominikanska-republika': 'do',
	dzibutsko: 'dj',
	egypt: 'eg',
	ekvador: 'ec',
	eritrea: 'er',
	estonsko: 'ee',
	etiopie: 'et',
	fidzi: 'fj',
	filipiny: 'ph',
	finsko: 'fi',
	francie: 'fr',
	gabon: 'ga',
	gambie: 'gm',
	ghana: 'gh',
	grenada: 'gd',
	gruzie: 'ge',
	guatemala: 'gt',
	guinea: 'gn',
	'guinea-bissau': 'gw',
	guyana: 'gy',
	haiti: 'ht',
	honduras: 'hn',
	chile: 'cl',
	chorvatsko: 'hr',
	indie: 'in',
	indonesie: 'id',
	irak: 'iq',
	iran: 'ir',
	irsko: 'ie',
	island: 'is',
	italie: 'it',
	izrael: 'il',
	jamajka: 'jm',
	japonsko: 'jp',
	jemen: 'ye',
	'jizni-afrika': 'za',
	'jizni-korea': 'kr',
	'jizni-sudan': 'ss',
	jordansko: 'jo',
	kambodza: 'kh',
	kamerun: 'cm',
	kanada: 'ca',
	kapverdy: 'cv',
	katar: 'qa',
	kazachstan: 'kz',
	kena: 'ke',
	kiribati: 'ki',
	kolumbie: 'co',
	komory: 'km',
	'konzska-republika': 'cg',
	kongo: 'cg',
	'konzska-demokraticka-republika': 'cd',
	'demokraticka-republika-kongo': 'cd',
	kosovo: 'xk',
	kostarika: 'cr',
	kuba: 'cu',
	kuvajt: 'kw',
	kypr: 'cy',
	kyrgyzstan: 'kg',
	laos: 'la',
	lesotho: 'ls',
	libanon: 'lb',
	liberie: 'lr',
	libye: 'ly',
	lichtenstejnsko: 'li',
	litva: 'lt',
	lotyssko: 'lv',
	lucembursko: 'lu',
	madagaskar: 'mg',
	madarsko: 'hu',
	malajsie: 'my',
	malawi: 'mw',
	maledivy: 'mv',
	mali: 'ml',
	malta: 'mt',
	maroko: 'ma',
	'marshallovy-ostrovy': 'mh',
	mauricius: 'mu',
	mauritanie: 'mr',
	mexiko: 'mx',
	mikronesie: 'fm',
	moldavsko: 'md',
	monako: 'mc',
	mongolsko: 'mn',
	mosambik: 'mz',
	'myanmar-(barma)': 'mm',
	namibie: 'na',
	nauru: 'nr',
	nemecko: 'de',
	nepal: 'np',
	niger: 'ne',
	nigerie: 'ng',
	nikaragua: 'ni',
	nizozemsko: 'nl',
	norsko: 'no',
	'novy-zeland': 'nz',
	oman: 'om',
	pakistan: 'pk',
	palau: 'pw',
	palestina: 'ps',
	panama: 'pa',
	'papua-nova-guinea': 'pg',
	paraguay: 'py',
	peru: 'pe',
	'pobrezi-slonoviny': 'ci',
	polsko: 'pl',
	portugalsko: 'pt',
	rakousko: 'at',
	'rovnikova-guinea': 'gq',
	rumunsko: 'ro',
	rusko: 'ru',
	rwanda: 'rw',
	recko: 'gr',
	salvador: 'sv',
	samoa: 'ws',
	'san-marino': 'sm',
	'saudska-arabie': 'sa',
	senegal: 'sn',
	'severni-korea': 'kp',
	'severni-makedonie': 'mk',
	makedonie: 'mk',
	seychely: 'sc',
	'sierra-leone': 'sl',
	singapur: 'sg',
	slovensko: 'sk',
	slovinsko: 'si',
	somalsko: 'so',
	'spojene-arabske-emiraty': 'ae',
	'spojene-kralovstvi': 'gb',
	'velka-britanie': 'gb',
	'spojene-staty-americke': 'us',
	srbsko: 'rs',
	'stredoafricka-republika': 'cf',
	sudan: 'sd',
	surinam: 'sr',
	'svata-lucie': 'lc',
	'svaty-krystof-a-nevis': 'kn',
	'svaty-tomas-a-princuv-ostrov': 'st',
	'svaty-tomas': 'st',
	'svaty-vincenc-a-grenadiny': 'vc',
	svazijsko: 'sz',
	syrie: 'sy',
	'salomounovy-ostrovy': 'sb',
	spanelsko: 'es',
	'sri-lanka': 'lk',
	svedsko: 'se',
	svycarsko: 'ch',
	tadzikistan: 'tj',
	tanzanie: 'tz',
	thajsko: 'th',
	'tchaj-wan': 'tw',
	togo: 'tg',
	tonga: 'to',
	'trinidad-a-tobago': 'tt',
	trinidad: 'tt',
	tunisko: 'tn',
	turecko: 'tr',
	turkmenistan: 'tm',
	tuvalu: 'tv',
	uganda: 'ug',
	ukrajina: 'ua',
	uruguay: 'uy',
	uzbekistan: 'uz',
	vanuatu: 'vu',
	vatikan: 'va',
	venezuela: 've',
	vietnam: 'vn',
	'vychodni-timor': 'tl',
	zambie: 'zm',
	zimbabwe: 'zw',

	// Spain parts
	katalansko: 'es_ct',
	galicie: 'es_ga',
	baskicko: 'es_pv',
	'kanarske-ostrovy': 'es_ci',

	// United Kingdom parts
	anglie: 'gb_eng',
	skotsko: 'gb_sct',
	wales: 'gb_wls',
	'severni-irsko': 'gb_nir',

	// Korunní závislá území (Crown Dependencies)
	guernsey: 'gg',
	jersey: 'je',
	'ostrov-man': 'im',

	// Britská zámořská teritoria (British Overseas Territories)
	'akrotiri-a-dekelia': 'akrotiri-and-dhekelia',
	anguilla: 'ai',
	bermudy: 'bm',
	'britske-antarkticke-uzemi': 'british-antarctic-territory',
	'britske-indickooceanske-uzemi': 'io',
	'britske-panenske-ostrovy': 'vg',
	falklandy: 'fk',
	gibraltar: 'gi',
	'kajmanske-ostrovy': 'ky',
	montserrat: 'ms',
	'pitcairnovy-ostrovy': 'pn',
	'svata-helena-ascension-a-tristan-da-cunha': 'sh',
	'jizni-georgie-a-jizni-sandwichovy-ostrovy': 'gs',
	'turks-a-caicos': 'tc',

	// Zámořské regiony a departementy (ROM / DOM)
	'francouzska-guyana': 'gf',
	guadeloupe: 'gp',
	martinik: 'mq',
	mayotte: 'yt',
	reunion: 're',

	// Zámořská společenství (COM)
	'francouzska-polynezie': 'pf',
	'saint-barthelemy': 'bl',
	'saint-martin': 'mf',
	'saint-pierre-a-miquelon': 'pm',
	'wallis-a-futuna': 'wf',

	// Zámořské území se zvláštním statusem (SUI / TAAF)
	'jihozapadni-ostrovy': 'tf',
	'nova-kaledonie': 'nc',
	'clippertonuv-ostrov': 'cp',

	// Teritoria USA
	'americka-samoa': 'as',
	'americke-panenske-ostrovy': 'vi',
	guam: 'gu',
	portoriko: 'pr',
	'severni-mariany': 'mp',
	'mensi-odlehle-ostrovy-usa': 'um',

	// Závislá území Nizozemska (Karibské Nizozemsko)
	aruba: 'aw',
	curacao: 'cw',
	'sint-maarten': 'sx',
	'bonaire-sint-eustatius-a-saba': 'bq',

	// Vnější teritoria Austrálie (Australian External Territories)
	'kokosove-ostrovy': 'cc',
	norfolk: 'nf',
	'vanocni-ostrov': 'cx',
	'hearduv-ostrov-a-mcdonaldovy-ostrovy': 'hm',
	'ostrovy-koraloveho-more': 'coral-sea-islands',
	'australske-antarkticke-uzemi': 'australian-antarctic-territory',

	// Teritoria a přidružené státy Nového Zélandu
	'cookovy-ostrovy': 'ck',
	niue: 'nu',
	tokelau: 'tk',
	rossadost: 'ross-dependency',

	// Dánské autonomní oblasti
	'faerske-ostrovy': 'fo',
	gronsko: 'gl',

	// Zvláštní správní oblasti Číny
	hongkong: 'hk',
	makao: 'mo',

	// Misc random suspicious stuff
	karibik: 'caribic',
};
