export const FILTER_DELAY = 500;
export const SELECT_ITEM_CELL = 'item-selection';
export const IS_DATE_FILTER = 'isDate';
export const IS_RANGE_DATE_FILTER = 'isRangeDate';

export enum AdminTableFilterType {
	AMOUNT = 'AMOUNT',
	DATE = 'DATE',
	RANGE_DATE = 'RANGE_DATE',
	DROPDOWN = 'DROPDOWN',
	TEXT = 'TEXT',
	YES_NO = 'YES_NO',
	NUMERIC = 'NUMERIC',
	MULTISELECT = 'MULTISELECT',
	DYNAMIC_COLUMNS = 'DYNAMIC_COLUMNS',
	SPECIFICATION = 'SPECIFICATION',
	BUNDLE_AUTOCOMPLETE = 'BUNDLE_AUTOCOMPLETE',
	ORDER_NUMBER_AUTOCOMPLETE = 'ORDER_NUMBER_AUTOCOMPLETE',
	SUPPLIER_AUTOCOMPLETE = 'SUPPLIER_AUTOCOMPLETE',
}
