export const JANUARY_FIRST_2038_IN_SECONDS = 2145916800;

export const RANGE_DATE_FILTER_DELIMITER = ':';
export const RANGE_DATE_FILTER_MIN_VALUE = '0';
export const RANGE_DATE_FILTER_MAX_VALUE = String(
	JANUARY_FIRST_2038_IN_SECONDS
);
