export const STORAGE_PREFIX = 'VINISTO_CLIENT_ADMIN';

export const LocalStorageKeys = {
	LOGIN_REDIRECT_PATH: 'LOGIN_REDIRECT_PATH',
	ACTIVE_SUPPLIER: 'ACTIVE_SUPPLIER',
	REGISTER_VALUES: 'REGISTER_VALUES',
	VINISTO_AUTH: 'VINISTO_AUTH',
	ACTIVE_LANGUAGE: 'ACTIVE_LANGUAGE',
} as const;
