import { VinistoProductDllModelsApiCategoryCategory } from 'vinisto_api_client/src/api-types/product-api/';

/**
 * @deprecated response types are autogenerated - replace appropriately
 */
interface GetSuppliersResponse {
	categories: VinistoProductDllModelsApiCategoryCategory[];
	count: number;
	error: unknown;
	isError: boolean;
}

export type { GetSuppliersResponse };
