import { GetSuppliersResponse } from './interfaces';

/**
 * @deprecated response types are autogenerated - this one should just be deleted
 */
function isGetSuppliersResponse(obj: any): obj is GetSuppliersResponse {
	return (
		obj &&
		Array.isArray(obj.categories) &&
		typeof obj.count === 'number' &&
		typeof obj.isError === 'boolean'
	);
}

export { isGetSuppliersResponse };
