export enum SpecificationType {
	CHECK_BOX = 'CHECK_BOX',
	MULTI_COMBO_BOX = 'MULTI_COMBO_BOX',
	COMBO_BOX = 'COMBO_BOX',
	NUMBER = 'NUMBER',
	NUMBER_IMPERIAL = 'NUMBER_IMPERIAL',
	DECIMAL_NUMBER = 'DECIMAL_NUMBER',
	DECIMAL_NUMBER_IMPERIAL = 'DECIMAL_NUMBER_IMPERIAL',
	TEXT = 'TEXT',
}
