/**
 * @deprecated here is VinistoHelperDllEnumsUserUserRights enum with the permissions. Use it instead.
 */
export const USER_ADMIN_USER = 'USER_ADMIN_USER';
export const USER_SUPPLIER = 'USER_SUPPLIER';
export const USER_CUSTOMER = 'USER_CUSTOMER';
export const USER_ADMIN_CATEGORY = 'USER_ADMIN_CATEGORY';
export const USER_ADMIN_EVALUATION = 'USER_ADMIN_EVALUATION';
export const USER_ADMIN = 'USER_ADMIN';
export const USER_ADMIN_PRODUCT = 'USER_ADMIN_PRODUCT';
export const USER_ADMIN_BUNDLE = 'USER_ADMIN_BUNDLE';
export const USER_ADMIN_HOMEPAGE = 'USER_ADMIN_HOMEPAGE';
export const USER_ADMIN_TAG = 'USER_ADMIN_TAG';
export const USER_ADMIN_SPECIFICATION = 'USER_ADMIN_SPECIFICATION';
export const USER_ADMIN_IMAGE = 'USER_ADMIN_IMAGE';
export const USER_ADMIN_ORDER = 'USER_ADMIN_ORDER';
export const USER_ADMIN_WAREHOUSE = 'USER_ADMIN_WAREHOUSE';
export const USER_ADMIN_CACHE = 'USER_ADMIN_CACHE';
export const USER_ADMIN_FEE_RULE = 'USER_ADMIN_FEE_RULE';
export const USER_ADMIN_DYNAMIC_FEE_RULE = 'USER_ADMIN_DYNAMIC_FEE_RULE';
export const USER_ADMIN_ORDER_FEES = 'USER_ADMIN_ORDER_FEES';
export const USER_ADMIN_SUPPLIER_CERTIFICATES =
	'USER_ADMIN_SUPPLIER_CERTIFICATES';
export const USER_ADMIN_FEE_RECORD = 'USER_ADMIN_FEE_RECORD';
export const USER_ADMIN_DISCOUNT = 'USER_ADMIN_DISCOUNT';
export const USER_ADMIN_BILLING = 'USER_ADMIN_BILLING';
export const USER_ADMIN_IMPORTER = 'USER_ADMIN_IMPORTER';
export const USER_FLEXI_BEE_EXPORT_ADMIN = 'USER_FLEXI_BEE_EXPORT_ADMIN';
export const USER_BANNER_EDITOR = 'USER_BANNER_EDITOR';
export const USER_COUPON_EDITOR = 'USER_COUPON_EDITOR';
export const USER_ORDER_STORNO = 'USER_ORDER_STORNO';
export const USER_ADMIN_CMS = 'USER_ADMIN_CMS';
export const USER_ADMIN_CMS_TAGS = 'USER_ADMIN_CMS_TAGS';
export const USER_ADMIN_STOCKING = 'USER_ADMIN_STOCKING';
export const USER_ADMIN_GIFT_RULE = 'USER_ADMIN_GIFT_RULE';
export const USER_ADMIN_PERMISSION = 'USER_ADMIN_PERMISSION';
export const USER_SELLER_COUPON_EDITOR = 'USER_SELLER_COUPON_EDITOR';
export const USER_ADMIN_SUBSCRIPTION = 'USER_ADMIN_SUBSCRIPTION';
