const modalsConfig = {
	LOGIN_MODAL: {
		animation: true,
		autoFocus: true,
		centered: true,
		contentClassName: '',
		dialogClassName: 'modal-dialog--login',
		enforceFocus: true,
		keyboard: true,
		restoreFocus: true,
		scrollable: false,
		bsPrefix: 'modal',
	},
	REGISTRATION_MODAL: {
		animation: true,
		autoFocus: true,
		centered: true,
		contentClassName: '',
		dialogClassName: 'modal-dialog--login',
		enforceFocus: true,
		keyboard: true,
		restoreFocus: true,
		scrollable: false,
		bsPrefix: 'modal',
	},
	FORGOTTEN_PASSWORD_MODAL: {
		animation: true,
		autoFocus: true,
		centered: true,
		contentClassName: '',
		dialogClassName: '',
		enforceFocus: true,
		keyboard: true,
		restoreFocus: true,
		scrollable: false,
		bsPrefix: 'modal',
	},
	REGISTRATION_CONFIRM_MODAL: {
		animation: true,
		autoFocus: true,
		centered: true,
		contentClassName: '',
		dialogClassName: '',
		enforceFocus: true,
		keyboard: true,
		restoreFocus: true,
		scrollable: false,
		bsPrefix: 'modal',
	},
	FORGOTTEN_PASSWORD_CONFIRM_MODAL: {
		animation: true,
		autoFocus: true,
		centered: true,
		contentClassName: '',
		dialogClassName: '',
		enforceFocus: true,
		keyboard: true,
		restoreFocus: true,
		scrollable: false,
		bsPrefix: 'modal',
	},
	ADDRESS_INVOICE_MODAL: {
		animation: true,
		autoFocus: true,
		centered: true,
		contentClassName: '',
		dialogClassName: 'modal-dialog--address',
		enforceFocus: true,
		keyboard: true,
		restoreFocus: true,
		scrollable: false,
		bsPrefix: 'modal',
	},
	ADDRESS_DELIVERY_MODAL: {
		animation: true,
		autoFocus: true,
		centered: true,
		contentClassName: '',
		dialogClassName: 'modal-dialog--address',
		enforceFocus: true,
		keyboard: true,
		restoreFocus: true,
		scrollable: false,
		bsPrefix: 'modal',
	},
	REVIEW_MODAL: {
		animation: true,
		autoFocus: true,
		centered: true,
		contentClassName: '',
		dialogClassName: 'modal-dialog--review',
		enforceFocus: true,
		keyboard: true,
		restoreFocus: true,
		scrollable: false,
		bsPrefix: 'modal',
	},
	PAYMENT_MODAL: {
		animation: true,
		autoFocus: true,
		centered: true,
		contentClassName: '',
		dialogClassName: 'modal-dialog--payment',
		enforceFocus: true,
		keyboard: true,
		restoreFocus: true,
		scrollable: false,
		bsPrefix: 'modal',
	},
	ADD_TO_BASKET_MODAL: {
		animation: true,
		autoFocus: true,
		centered: true,
		contentClassName: '',
		dialogClassName: '',
		enforceFocus: true,
		keyboard: true,
		restoreFocus: true,
		scrollable: false,
		bsPrefix: 'modal',
	},
	CONFIRM_DIALOG: {
		animation: true,
		autoFocus: true,
		centered: true,
		contentClassName: '',
		dialogClassName: 'modal-dialog--confirm',
		enforceFocus: true,
		keyboard: true,
		restoreFocus: true,
		scrollable: false,
		bsPrefix: 'modal',
	},
	ZASILKOVNA_MODAL: {
		animation: true,
		autoFocus: true,
		centered: true,
		contentClassName: 'bg-transparent shadow-none',
		dialogClassName: '',
		bodyClassName: 'bg-transparent p-0',
		enforceFocus: true,
		keyboard: true,
		restoreFocus: true,
		scrollable: false,
		bsPrefix: 'modal',
		closeButton: false,
	},
	PPL_MODAL: {
		animation: true,
		autoFocus: true,
		centered: true,
		contentClassName: '',
		dialogClassName: 'modal-dialog--ppl',
		bodyClassName: '',
		enforceFocus: true,
		keyboard: true,
		restoreFocus: true,
		scrollable: false,
		bsPrefix: 'modal',
		closeButton: true,
	},
	DPD_MODAL: {
		animation: true,
		autoFocus: true,
		centered: true,
		contentClassName: '',
		dialogClassName: 'modal-dialog--dpd',
		bodyClassName: '',
		enforceFocus: true,
		keyboard: true,
		restoreFocus: true,
		scrollable: false,
		bsPrefix: 'modal',
		closeButton: true,
	},
	CANCEL_ORDER_CONFIRM_MODAL: { centered: true },
	FILL_NICKNAME_MODAL: { centered: true },
	CROSS_SELL_MODAL: {
		animation: true,
		autoFocus: true,
		centered: false,
		contentClassName: '',
		dialogClassName: 'modal-dialog--cross-sell',
		enforceFocus: true,
		keyboard: true,
		restoreFocus: true,
		scrollable: false,
		bsPrefix: 'modal',
	},
	BASKET_SHARE_MODAL: { centered: true },
	QUICK_PURCHASE_MODAL: {
		centered: true,
		dialogClassName: 'modal-dialog--quick-purchase',
	},
	JOIN_VINISTO_PLUS_MODAL: {
		centered: true,
		dialogClassName: 'modal-dialog--join-vinisto-plus mobile-modal',
	},
	GUARANTEE_PRICE_MODAL: {
		dialogClassName: 'modal-dialog--guarantee-price mobile-modal',
	},
	GUARANTEE_OK_MODAL: {
		dialogClassName: 'modal-dialog--guarantee-ok mobile-modal',
	},
	VINISTO_PLUS_BASKET_LOGIN_MODAL: {
		dialogClassName: 'modal-dialog--vinisto-plus-basket-modal mobile-modal',
	},
	VINISTO_PLUS_BASKET_REGISTER_MODAL: {
		dialogClassName: 'modal-dialog--vinisto-plus-basket-modal mobile-modal',
	},
	BASKET_WAITING_FOR_APPROVAL_CONFIRM_MODAL: {
		dialogClassName: 'mobile-modal',
	},
	REQUEST_CREDIT_INCREASE_MODAL: {
		dialogClassName:
			'modal-dialog--request-credit-increase-modal  mobile-modal',
	},
	PLATFORM_MISMATCH_MODAL: {
		autoFocus: true,
		centered: true,
		dialogClassName: 'mobile-modal',
		enforceFocus: true,
		keyboard: false,
		restoreFocus: true,
		scrollable: false,
		closeButton: false,
		closeOnBackdropClick: false,
	},
};

export default modalsConfig;
