export const REGISTRATION_MODAL = 'REGISTRATION_MODAL';
export const REGISTRATION_CONFIRM_MODAL = 'REGISTRATION_CONFIRM_MODAL';
export const LOGIN_MODAL = 'LOGIN_MODAL';
export const FORGOTTEN_PASSWORD_MODAL = 'FORGOTTEN_PASSWORD_MODAL';
export const FORGOTTEN_PASSWORD_CONFIRM_MODAL =
	'FORGOTTEN_PASSWORD_CONFIRM_MODAL';
export const ADDRESS_INVOICE_MODAL = 'ADDRESS_INVOICE_MODAL';
export const ADDRESS_DELIVERY_MODAL = 'ADDRESS_DELIVERY_MODAL';
export const REVIEW_MODAL = 'REVIEW_MODAL';
export const FILL_NICKNAME_MODAL = 'FILL_NICKNAME_MODAL';
export const PAYMENT_MODAL = 'PAYMENT_MODAL';
export const ADD_TO_BASKET_MODAL = 'ADD_TO_BASKET_MODAL';
export const CONFIRM_DIALOG = 'CONFIRM_DIALOG';
export const ZASILKOVNA_MODAL = 'ZASILKOVNA_MODAL';
export const PPL_MODAL = 'PPL_MODAL';
export const DPD_MODAL = 'DPD_MODAL';
export const CANCEL_ORDER_CONFIRM_MODAL = 'CANCEL_ORDER_CONFIRM_MODAL';
export const CROSS_SELL_MODAL = 'CROSS_SELL_MODAL';
export const BASKET_SHARE_MODAL = 'BASKET_SHARE_MODAL';
export const QUICK_PURCHASE_MODAL = 'QUICK_PURCHASE_MODAL';
export const JOIN_VINISTO_PLUS_MODAL = 'JOIN_VINISTO_PLUS_MODAL';
export const GUARANTEE_PRICE_MODAL = 'GUARANTEE_PRICE_MODAL';
export const GUARANTEE_OK_MODAL = 'GUARANTEE_OK_MODAL';
export const VINISTO_PLUS_BASKET_LOGIN_MODAL =
	'VINISTO_PLUS_BASKET_LOGIN_MODAL';
export const VINISTO_PLUS_BASKET_REGISTER_MODAL =
	'VINISTO_PLUS_BASKET_REGISTER_MODAL';
export const BASKET_WAITING_FOR_APPROVAL_CONFIRM_MODAL =
	'BASKET_WAITING_FOR_APPROVAL_CONFIRM_MODAL';
export const REQUEST_CREDIT_INCREASE_MODAL = 'REQUEST_CREDIT_INCREASE_MODAL';
export const PLATFORM_MISMATCH_MODAL = 'PLATFORM_MISMATCH_MODAL';

export const DEFAULT_CLOSING_TIMEOUT = 100;
export const SAFE_REOPEN_TIMEOUT = 200;
