export const Actions = {
	LOGIN_FROM_ADMIN: 'LOGIN_FROM_ADMIN',
	LOGIN_FROM_ADMIN_SUCCESS: 'LOGIN_FROM_ADMIN_SUCCESS',
	LOGOUT_FROM_ESHOP: 'LOGOUT_FROM_ESHOP',
	CREATE_NEW_BASKET_FROM_ADMIN: 'CREATE_NEW_BASKET_FROM_ADMIN',
	DELETE_BASKET_FROM_ADMIN: 'DELETE_BASKET_FROM_ADMIN',
	DELETE_BASKET_FROM_ADMIN_SUCCESS: 'DELETE_BASKET_FROM_ADMIN_SUCCESS',
	SET_BASKET_ID: 'SET_BASKET_ID',
	RESET_BASKET_FROM_ESHOP: 'RESET_BASKET_FROM_ESHOP',
} as const;

export type Action = (typeof Actions)[keyof typeof Actions];
