export const SPECIFICATION_TYPE_TEXT = 'TEXT';
export const SPECIFICATION_TYPE_MULTI_COMBO_BOX = 'MULTI_COMBO_BOX';
export const SPECIFICATION_TYPE_COMBO_BOX = 'COMBO_BOX';
export const SPECIFICATION_TYPE_CHECK_BOX = 'CHECK_BOX';
